name: Check build, lint & unit test

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Load keys from secrets
        env:
          API_KEY: ${{ secrets.API_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        run: printf "API_KEY=\"$API_KEY\"\nBASE_URL=\"$BASE_URL\"\nMAPS_API_KEY=\"$MAPS_API_KEY\"" > ./local.properties

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Caching gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Copy gradle properties file
        run:  mkdir -p ~/.gradle ; 
              cp .github/gradle/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Move google-services.json to App folder
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICE }}
        run:  touch ./app/google-services.json ;
              echo "$GOOGLE_SERVICES" | base64 --decode > ./app/google-services.json

      - name: Build the app
        run: ./gradlew assembleDebug

      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: debug apk
          path: app/build/outputs/apk/debug/

  test:
    runs-on: ubuntu-latest
    needs: build
    environment: staging
    if: ${{ github.actor != 'dependabot[bot]' }}

    permissions:
      security-events: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Load keys from secrets
        env:
          API_KEY: ${{ secrets.API_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        run: printf "API_KEY=\"$API_KEY\"\nBASE_URL=\"$BASE_URL\"\nMAPS_API_KEY=\"$MAPS_API_KEY\"" > ./local.properties

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Caching gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Copy gradle properties file
        run:  mkdir -p ~/.gradle ; 
              cp .github/gradle/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Move google-services.json to App folder
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICE }}
        run:  touch ./app/google-services.json ;
              echo "$GOOGLE_SERVICES" | base64 --decode > app/google-services.json

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: security-extended

      - name: Run unit test
        run: ./gradlew test --stacktrace

      - name: Run detekt
        run: ./gradlew detekt

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: Test-Reports
          path: reports/detekt.html
        if: always()

      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: reports/detekt.sarif
